last_names: dict[str : list[str, ...]] = {
    "Hispanic": [
        "Garcia",
        "Rodriguez",
        "Lopez",
        "Hernandez",
        "Martinez",
        "Perez",
        "Gonzalez",
        "Torres",
    ],
    "Slavic": [
        "Kovac",
        "Novak",
        "Petrov",
        "Vasiliev",
        "Sokolov",
        "Popov",
        "Kuznetsov",
        "Ivanov",
    ],
    "African": [
        "Okafor",
        "Diallo",
        "Ouedraogo",
        "Keita",
        "Diop",
        "Nkrumah",
        "Sow",
        "Chukwu",
    ],
    "Asian": ["Tanaka", "Kim", "Singh", "Li", "Wong", "Patel", "Nguyen", "Chen"],
}
